config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :attendees
  end

  root 'events#index'
  get '/create_event', to: 'events#new'
  get '/check_into_event', to: 'attendees#new'
  post '/check_into_event', to: 'attendees#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event

  default_scope -> { order(created_at: :desc) }
  before_save { email.downcase! }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :event_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendees, dependent: :destroy
  accepts_nested_attributes_for :attendees

  validates :name, presence: true, length: { maximum: 50 }
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  def index
    @attendees = Attendee.all
  end

  def show
    @attendee = Attendee.find(params[:id])
  end

  def new
    @attendee = Attendee.new
  end

  def create
    @attendee = Attendee.create(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to root_path, notice: "Check in was successful." }
      else
        format.html { render :new }
      end
    end
  end

  private

    def attendee_params
      params.require(:attendee).permit(:email, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: "Event was successfully created." }
      else
        format.html { render :new }
      end
    end

  end

  def destroy
    @event = Event.find(params[:id])

    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Event was successfully canceled." }
    end
  end

  private

    def event_params
      params.require(:event).permit(:name, :start_time, :end_time, attendees_attributes: [:id, :email, :created_at ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/attendees/_attendee.html.erb
<li id = "attendee - <%= attendee.id %>">
  <span class = "email"><%= attendee.email %> &nbsp &nbsp &nbsp </span>
  <span class = "timestamp"><%= attendee.created_at %></span>
</li>

app/views/attendees/_error_messages.html.erb
<% if @attendee.errors.any? %>
  <div id = "error explanation">
    <div class = "alert alert-danger">
      <h4><%= pluralize(@attendee.errors.count, "error") %> prohibited this event from being saved: </h4>
    </div>
    <ul>
    <% @attendee.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/attendees/_form.html.erb
<%= form_for :attendee do |form| %>

  <%= render 'error_messages' %>

  <div class = "field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class = "field">
    <%= form.label "List of Events" %>
    <%= form.collection_radio_buttons :event_id, Event.all, :id, :name do |b| %>
      <div class = "collection-radio-button">
        <%= b.radio_button %>
        <%= b.label %>
      </div>
    <% end %>
  </div>

  <div class = "actions">
    <%= form.submit "Check into Event", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/attendees/index.html.erb
<h1> List of Attendees </h1>

<table>
  <thead>
    <tr>
      <th> Emails </th>
      <th> Check in Time </th>
      <th colspan = "3"></th>
    </tr>
  </thead>

  <tbody>
  <% @attendees.each do |attendee| %>
    <tr>
      <td><%= attendee.email %></td>
      <td><%= attendee.created_at %></td>
      <td><%= link_to "Show", event_attendees_path %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/attendees/new.html.erb
<% provide(:title, "Check into Event") %>
<h1> Check into Event </h1>

<%= render "form", attendee: @attendee %>

<%= link_to "Back", root_path %>

app/views/attendees/show.html.erb
<% provide(:title, @attendee.email) %>
  <p id = "notice"><%= notice %></p>

<p>
  <strong> Email: </strong>
  <%= @attendee.email %>
</p>

<p>
  <strong> Check in Time: </strong>
  <%= @attendee.created_at %>
</p>

<p>
  <strong> Event ID: </strong>
  <%= @attendee.event_id %>
</p>

<%= link_to 'Back', root_path %>

app/views/events/_error_messages.html.erb
<% if @event.errors.any? %>
  <div id = "error explanation">
    <div class = "alert alert-danger">
      <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved: </h4>
    </div>
    <ul>
    <% @event.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event do |form| %>

  <%= render "error_messages" %>

  <div class = "field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class = "field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class = "field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class = "actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<% provide(:title, "List of Events") %>
<h1> List of Events </h1>

<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Start Time </th>
      <th> End Time </th>
      <th colspan = "3"></th>
    </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.start_time %></td>
      <td><%= event.end_time %></td>
      <td><%= link_to "Show", event %></td>
      <td><%= link_to "Cancel", event, method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<p><%= link_to "Create New Event", create_event_path, class: "btn btn-large btn-primary" %>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<%= link_to "Check into Event", check_into_event_path, class: "btn btn-large btn-primary" %></p>

app/views/events/new.html.erb
<% provide(:title, "Create Event") %>
<h1> Create Event </h1>

<%= render "form", event: @event %>

<%= link_to "Back", root_path %>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
  <p id = "notice"><%= notice %></p>

<p>
  <strong> Name: </strong>
  <%= @event.name %>
</p>

<p>
  <strong> Start Time: </strong>
  <%= @event.start_time %>
</p>

<p>
  <strong> End Time: </strong>
  <%= @event.end_time %>
</p>

<% if @event.attendees.any? %>
  <h3> Attendees (<%= @event.attendees.count %>)</h3>
  <ol class = "attendees" >
    <%= render @attendees %>
  </ol>
<% end %>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>